// Metacritic critic scores matched against title + release year. Snapshot: 2026-08-04.
// score=null means the title page exists but has no published Metascore, or no page was found.
window.METACRITIC_DATA = {
"#Alive|2020":{"score":56,"slug":"alive","status":"scored"},
"10 Cloverfield Lane|2016":{"score":76,"slug":"10-cloverfield-lane","status":"scored"},
"13 Tzameti|2005":{"score":61,"slug":"13-tzameti","status":"scored"},
"1408|2007":{"score":64,"slug":"1408","status":"scored"},
"1922|2017":{"score":70,"slug":"1922","status":"scored"},
"28 Weeks Later|2007":{"score":78,"slug":"28-weeks-later","status":"scored"},
"28 Years Later: The Bone Temple|2026":{"score":81,"slug":"28-years-later-the-bone-temple","status":"scored"},
"30 Days of Night|2007":{"score":53,"slug":"30-days-of-night","status":"scored"},
"A Dark Song|2016":{"score":71,"slug":"a-dark-song","status":"scored"},
"A Different Man|2024":{"score":78,"slug":"a-different-man","status":"scored"},
"A Girl Walks Home Alone at Night|2014":{"score":81,"slug":"a-girl-walks-home-alone-at-night","status":"scored"},
"A Hijacking|2012":{"score":82,"slug":"a-hijacking","status":"scored"},
"A History of Violence|2005":{"score":82,"slug":"a-history-of-violence","status":"scored"},
"A Most Violent Year|2014":{"score":79,"slug":"a-most-violent-year","status":"scored"},
"A Perfect Getaway|2009":{"score":63,"slug":"a-perfect-getaway","status":"scored"},
"A Prophet|2009":{"score":90,"slug":"a-prophet","status":"scored"},
"A Quiet Place Part II|2021":{"score":71,"slug":"a-quiet-place-part-ii","status":"scored"},
"A Quiet Place: Day One|2024":{"score":68,"slug":"a-quiet-place-day-one","status":"scored"},
"A Quiet Place|2018":{"score":82,"slug":"a-quiet-place","status":"scored"},
"Abigail|2024":{"score":62,"slug":"abigail","status":"scored"},
"Absentia|2011":{"score":null,"slug":null,"status":"not-found"},
"Afflicted|2013":{"score":56,"slug":"afflicted","status":"scored"},
"Afraid|2024":{"score":28,"slug":"afraid","status":"scored"},
"Alien: Covenant|2017":{"score":65,"slug":"alien-covenant","status":"scored"},
"Alien: Romulus|2024":{"score":64,"slug":"alien-romulus","status":"scored"},
"Alone|2020":{"score":70,"slug":"alone","status":"scored"},
"Anatomy of a Fall|2023":{"score":86,"slug":"anatomy-of-a-fall","status":"scored"},
"Animal Kingdom|2010":{"score":83,"slug":"animal-kingdom","status":"scored"},
"Annabelle: Creation|2017":{"score":62,"slug":"annabelle-creation","status":"scored"},
"Annihilation|2018":{"score":79,"slug":"annihilation","status":"scored"},
"Antebellum|2020":{"score":43,"slug":"antebellum","status":"scored"},
"Antlers|2021":{"score":57,"slug":"antlers","status":"scored"},
"Apartment 7A|2024":{"score":49,"slug":"apartment-7a","status":"scored"},
"Apocalypto|2006":{"score":68,"slug":"apocalypto","status":"scored"},
"Apostle|2018":{"score":62,"slug":"apostle","status":"scored"},
"Appendage|2023":{"score":65,"slug":"appendage","status":"scored"},
"Arbitrage|2012":{"score":73,"slug":"arbitrage","status":"scored"},
"Arcadian|2024":{"score":57,"slug":"arcadian","status":"scored"},
"Argo|2012":{"score":86,"slug":"argo","status":"scored"},
"As Above So Below|2014":{"score":39,"slug":"as-above-so-below","status":"scored"},
"Ash|2025":{"score":63,"slug":"ash","status":"scored"},
"Attachment|2022":{"score":64,"slug":"attachment","status":"scored"},
"Attack the Block|2011":{"score":75,"slug":"attack-the-block","status":"scored"},
"Azrael|2024":{"score":52,"slug":"azrael","status":"scored"},
"Backrooms|2026":{"score":77,"slug":"backrooms","status":"scored"},
"Bad Genius|2017":{"score":null,"slug":"bad-genius","status":"no-score"},
"Barbarian|2022":{"score":78,"slug":"barbarian","status":"scored"},
"Baskin|2015":{"score":58,"slug":"baskin","status":"scored"},
"Beau Is Afraid|2023":{"score":63,"slug":"beau-is-afraid","status":"scored"},
"Becky|2020":{"score":54,"slug":"becky","status":"scored"},
"Bedevilled|2010":{"score":null,"slug":null,"status":"not-found"},
"Before the Devil Knows You're Dead|2007":{"score":86,"slug":"before-the-devil-knows-youre-dead","status":"scored"},
"Behind the Mask: The Rise of Leslie Vernon|2006":{"score":66,"slug":"behind-the-mask-the-rise-of-leslie-vernon","status":"scored"},
"Berberian Sound Studio|2012":{"score":80,"slug":"berberian-sound-studio","status":"scored"},
"Berlin Syndrome|2017":{"score":70,"slug":"berlin-syndrome","status":"scored"},
"Better Watch Out|2016":{"score":67,"slug":"better-watch-out","status":"scored"},
"Big Bad Wolves|2013":{"score":64,"slug":"big-bad-wolves","status":"scored"},
"Bird Box|2018":{"score":51,"slug":"bird-box","status":"scored"},
"Birth/Rebirth|2023":{"score":null,"slug":null,"status":"not-found"},
"Black Book|2006":{"score":71,"slug":"black-book","status":"scored"},
"Black Christmas|2006":{"score":22,"slug":"black-christmas","status":"scored"},
"Black Swan|2010":{"score":79,"slug":"black-swan","status":"scored"},
"Blair Witch|2016":{"score":47,"slug":"blair-witch","status":"scored"},
"Blink Twice|2024":{"score":66,"slug":"blink-twice","status":"scored"},
"Blue Ruin|2013":{"score":78,"slug":"blue-ruin","status":"scored"},
"Bodies Bodies Bodies|2022":{"score":69,"slug":"bodies-bodies-bodies","status":"scored"},
"Boiling Point|2021":{"score":50,"slug":"boiling-point","status":"scored"},
"Bone Tomahawk|2015":{"score":72,"slug":"bone-tomahawk","status":"scored"},
"Boogeyman|2005":{"score":32,"slug":"boogeyman","status":"scored"},
"Border|2018":{"score":75,"slug":"border","status":"scored"},
"Brawl in Cell Block 99|2017":{"score":79,"slug":"brawl-in-cell-block-99","status":"scored"},
"Breach|2007":{"score":74,"slug":"breach","status":"scored"},
"Brick|2005":{"score":72,"slug":"brick","status":"scored"},
"Brightburn|2019":{"score":44,"slug":"brightburn","status":"scored"},
"Bring Her Back|2025":{"score":75,"slug":"bring-her-back","status":"scored"},
"Broadcast Signal Intrusion|2021":{"score":null,"slug":"broadcast-signal-intrusion","status":"no-score"},
"Bug|2006":{"score":62,"slug":"bug","status":"scored"},
"Bullhead|2011":{"score":68,"slug":"bullhead","status":"scored"},
"Buried|2010":{"score":65,"slug":"buried","status":"scored"},
"Burning|2018":{"score":91,"slug":"burning","status":"scored"},
"Byzantium|2012":{"score":66,"slug":"byzantium","status":"scored"},
"Cache|2005":{"score":null,"slug":null,"status":"not-found"},
"Caché|2005":{"score":null,"slug":null,"status":"not-found"},
"Calibre|2018":{"score":76,"slug":"calibre","status":"scored"},
"Cam|2018":{"score":71,"slug":"cam","status":"scored"},
"Candyman|2021":{"score":61,"slug":"candyman","status":"scored"},
"Captain Phillips|2013":{"score":82,"slug":"captain-phillips","status":"scored"},
"Captivity|2007":{"score":24,"slug":"captivity","status":"scored"},
"Cargo|2017":{"score":47,"slug":"cargo","status":"scored"},
"Carriers|2009":{"score":null,"slug":"carriers","status":"no-score"},
"Casino Royale|2006":{"score":80,"slug":"casino-royale","status":"scored"},
"Caveat|2020":{"score":60,"slug":"caveat","status":"scored"},
"Censor|2021":{"score":69,"slug":"censor","status":"scored"},
"Cheap Thrills|2013":{"score":63,"slug":"cheap-thrills","status":"scored"},
"Children of Men|2006":{"score":84,"slug":"children-of-men","status":"scored"},
"Christmas Bloody Christmas|2022":{"score":46,"slug":"christmas-bloody-christmas","status":"scored"},
"Chronicle|2012":{"score":69,"slug":"chronicle-2012","status":"scored"},
"Chum|2026":{"score":null,"slug":"chum","status":"no-score"},
"Civil War|2024":{"score":75,"slug":"civil-war","status":"scored"},
"Climax|2018":{"score":69,"slug":"climax","status":"scored"},
"Cloverfield|2008":{"score":64,"slug":"cloverfield","status":"scored"},
"Clown in a Cornfield|2025":{"score":55,"slug":"clown-in-a-cornfield","status":"scored"},
"Cobweb|2023":{"score":52,"slug":"cobweb","status":"scored"},
"Coherence|2013":{"score":65,"slug":"coherence","status":"scored"},
"Cold Storage|2026":{"score":64,"slug":"cold-storage","status":"scored"},
"Cold in July|2014":{"score":73,"slug":"cold-in-july","status":"scored"},
"Color Out of Space|2019":{"score":70,"slug":"color-out-of-space","status":"scored"},
"Come True|2020":{"score":68,"slug":"come-true","status":"scored"},
"Coming Home in the Dark|2021":{"score":64,"slug":"coming-home-in-the-dark","status":"scored"},
"Companion|2025":{"score":70,"slug":"companion","status":"scored"},
"Compliance|2012":{"score":68,"slug":"compliance","status":"scored"},
"Confessions|2010":{"score":null,"slug":null,"status":"not-found"},
"Contagion|2011":{"score":70,"slug":"contagion","status":"scored"},
"Cop Car|2015":{"score":66,"slug":"cop-car","status":"scored"},
"Crank|2006":{"score":57,"slug":"crank","status":"scored"},
"Crawl|2019":{"score":60,"slug":"crawl","status":"scored"},
"Creep 2|2017":{"score":75,"slug":"creep-2","status":"scored"},
"Creep|2014":{"score":74,"slug":"creep","status":"scored"},
"Crimes of the Future|2022":{"score":68,"slug":"crimes-of-the-future","status":"scored"},
"Crimson Peak|2015":{"score":66,"slug":"crimson-peak","status":"scored"},
"Cry Wolf|2005":{"score":null,"slug":null,"status":"not-found"},
"Cuckoo|2024":{"score":62,"slug":"cuckoo","status":"scored"},
"Dark Harvest|2023":{"score":51,"slug":"dark-harvest","status":"scored"},
"Dark Water|2005":{"score":52,"slug":"dark-water","status":"scored"},
"Dawn of the Planet of the Apes|2014":{"score":79,"slug":"dawn-of-the-planet-of-the-apes","status":"scored"},
"Daybreakers|2009":{"score":57,"slug":"daybreakers","status":"scored"},
"Dead Snow|2009":{"score":61,"slug":"dead-snow","status":"scored"},
"Deadstream|2022":{"score":67,"slug":"deadstream","status":"scored"},
"Death Proof|2007":{"score":null,"slug":null,"status":"not-found"},
"Decision to Leave|2022":{"score":85,"slug":"decision-to-leave","status":"scored"},
"Deepwater Horizon|2016":{"score":68,"slug":"deepwater-horizon","status":"scored"},
"Deliver Us from Evil|2014":{"score":86,"slug":"deliver-us-from-evil","status":"scored"},
"Derailed|2005":{"score":40,"slug":"derailed","status":"scored"},
"Devil|2010":{"score":44,"slug":"devil","status":"scored"},
"District 9|2009":{"score":81,"slug":"district-9","status":"scored"},
"Disturbia|2007":{"score":62,"slug":"disturbia","status":"scored"},
"Doctor Sleep|2019":{"score":59,"slug":"doctor-sleep","status":"scored"},
"Don't Breathe|2016":{"score":71,"slug":"dont-breathe","status":"scored"},
"Don't Move|2024":{"score":59,"slug":"dont-move","status":"scored"},
"Dracula|2026":{"score":44,"slug":"dracula-2026","status":"scored"},
"Drag Me to Hell|2009":{"score":83,"slug":"drag-me-to-hell","status":"scored"},
"Dream Home|2010":{"score":null,"slug":null,"status":"not-found"},
"Dredd|2012":{"score":60,"slug":"dredd","status":"scored"},
"Drive|2011":{"score":79,"slug":"drive","status":"scored"},
"Drop|2025":{"score":65,"slug":"drop","status":"scored"},
"Eastern Promises|2007":{"score":83,"slug":"eastern-promises","status":"scored"},
"Eden Lake|2008":{"score":65,"slug":"eden-lake","status":"scored"},
"Elle|2016":{"score":89,"slug":"elle","status":"scored"},
"Emelie|2015":{"score":62,"slug":"emelie","status":"scored"},
"Emily the Criminal|2022":{"score":75,"slug":"emily-the-criminal","status":"scored"},
"End of Watch|2012":{"score":68,"slug":"end-of-watch","status":"scored"},
"Enemy|2013":{"score":61,"slug":"enemy","status":"scored"},
"Enys Men|2022":{"score":78,"slug":"enys-men","status":"scored"},
"Escape Room|2019":{"score":48,"slug":"escape-room","status":"scored"},
"Europa Report|2013":{"score":68,"slug":"europa-report","status":"scored"},
"Evil Dead Rise|2023":{"score":69,"slug":"evil-dead-rise","status":"scored"},
"Evil Dead|2013":{"score":57,"slug":"evil-dead-2013","status":"scored"},
"Ex Machina|2014":{"score":78,"slug":"ex-machina","status":"scored"},
"Exam|2009":{"score":null,"slug":null,"status":"not-found"},
"Exhuma|2024":{"score":80,"slug":"exhuma","status":"scored"},
"Faces of Death|2026":{"score":63,"slug":"faces-of-death","status":"scored"},
"Fall|2022":{"score":49,"slug":"fall","status":"scored"},
"Fear Street Part One: 1994|2021":{"score":67,"slug":"fear-street-part-one-1994","status":"scored"},
"Fear Street Part Three: 1666|2021":{"score":68,"slug":"fear-street-part-three-1666","status":"scored"},
"Fear Street Part Two: 1978|2021":{"score":61,"slug":"fear-street-part-two-1978","status":"scored"},
"Fido|2006":{"score":70,"slug":"fido","status":"scored"},
"Final Destination 3|2006":{"score":43,"slug":"final-destination-3","status":"scored"},
"Final Destination 5|2011":{"score":50,"slug":"final-destination-5","status":"scored"},
"Final Destination Bloodlines|2025":{"score":73,"slug":"final-destination-bloodlines","status":"scored"},
"Five Nights at Freddy's|2023":{"score":33,"slug":"five-nights-at-freddys","status":"scored"},
"Flightplan|2005":{"score":53,"slug":"flightplan","status":"scored"},
"Forbidden Fruits|2026":{"score":56,"slug":"forbidden-fruits","status":"scored"},
"Forgotten|2017":{"score":null,"slug":null,"status":"not-found"},
"Fracture|2007":{"score":68,"slug":"fracture","status":"scored"},
"Freaky|2020":{"score":67,"slug":"freaky","status":"scored"},
"Fresh|2022":{"score":81,"slug":"fresh","status":"scored"},
"Frozen|2010":{"score":43,"slug":"frozen","status":"scored"},
"Funny Games|2007":{"score":44,"slug":"funny-games","status":"scored"},
"Gaia|2021":{"score":64,"slug":"gaia","status":"scored"},
"Gerald's Game|2017":{"score":77,"slug":"geralds-game","status":"scored"},
"Get Out|2017":{"score":85,"slug":"get-out","status":"scored"},
"Glorious|2022":{"score":60,"slug":"glorious","status":"scored"},
"Godzilla Minus One|2023":{"score":81,"slug":"godzilla-minus-one","status":"scored"},
"Gone Baby Gone|2007":{"score":72,"slug":"gone-baby-gone","status":"scored"},
"Gone Girl|2014":{"score":79,"slug":"gone-girl","status":"scored"},
"Good Time|2017":{"score":80,"slug":"good-time","status":"scored"},
"Goodnight Mommy|2014":{"score":81,"slug":"goodnight-mommy","status":"scored"},
"Grabbers|2012":{"score":62,"slug":"grabbers","status":"scored"},
"Grave Encounters|2011":{"score":33,"slug":"grave-encounters","status":"scored"},
"Green Room|2015":{"score":79,"slug":"green-room","status":"scored"},
"Halloween|2018":{"score":67,"slug":"halloween-2018","status":"scored"},
"Hanna|2011":{"score":65,"slug":"hanna","status":"scored"},
"Hard Candy|2005":{"score":58,"slug":"hard-candy","status":"scored"},
"Haunt|2019":{"score":33,"slug":"haunt","status":"scored"},
"Headhunters|2011":{"score":null,"slug":null,"status":"not-found"},
"Heart Eyes|2025":{"score":61,"slug":"heart-eyes","status":"scored"},
"Hellraiser|2022":{"score":56,"slug":"hellraiser","status":"scored"},
"Hereditary|2018":{"score":87,"slug":"hereditary","status":"scored"},
"Heretic|2024":{"score":71,"slug":"heretic","status":"scored"},
"His House|2020":{"score":72,"slug":"his-house","status":"scored"},
"Hokum|2026":{"score":76,"slug":"hokum","status":"scored"},
"Hold Your Breath|2024":{"score":45,"slug":"hold-your-breath","status":"scored"},
"Hold the Dark|2018":{"score":63,"slug":"hold-the-dark","status":"scored"},
"Hostel|2005":{"score":55,"slug":"hostel","status":"scored"},
"Host|2020":{"score":73,"slug":"host","status":"scored"},
"Hounds of Love|2016":{"score":73,"slug":"hounds-of-love","status":"scored"},
"House of Wax|2005":{"score":41,"slug":"house-of-wax","status":"scored"},
"Housebound|2014":{"score":76,"slug":"housebound","status":"scored"},
"Huesera: The Bone Woman|2022":{"score":81,"slug":"huesera-the-bone-woman","status":"scored"},
"Hunter Hunter|2020":{"score":61,"slug":"hunter-hunter","status":"scored"},
"Hush|2016":{"score":18,"slug":"hush","status":"scored"},
"I Am Legend|2007":{"score":65,"slug":"i-am-legend","status":"scored"},
"I Am Not a Serial Killer|2016":{"score":54,"slug":"i-am-not-a-serial-killer","status":"scored"},
"I Am the Pretty Thing That Lives in the House|2016":{"score":68,"slug":"i-am-the-pretty-thing-that-lives-in-the-house","status":"scored"},
"I Saw the Devil|2010":{"score":67,"slug":"i-saw-the-devil","status":"scored"},
"I Saw the TV Glow|2024":{"score":86,"slug":"i-saw-the-tv-glow","status":"scored"},
"I Spit on Your Grave|2010":{"score":27,"slug":"i-spit-on-your-grave","status":"scored"},
"Immaculate|2024":{"score":57,"slug":"immaculate","status":"scored"},
"Imperium|2016":{"score":68,"slug":"imperium","status":"scored"},
"Impetigore|2019":{"score":null,"slug":null,"status":"not-found"},
"In a Violent Nature|2024":{"score":68,"slug":"in-a-violent-nature","status":"scored"},
"Incantation|2022":{"score":null,"slug":null,"status":"not-found"},
"Inception|2010":{"score":74,"slug":"inception","status":"scored"},
"Infinity Pool|2023":{"score":72,"slug":"infinity-pool","status":"scored"},
"Influencer|2022":{"score":66,"slug":"influencer","status":"scored"},
"Inside Man|2006":{"score":76,"slug":"inside-man","status":"scored"},
"Inside|2007":{"score":36,"slug":"inside","status":"scored"},
"Insidious: The Red Door|2023":{"score":45,"slug":"insidious-the-red-door","status":"scored"},
"Insidious|2010":{"score":52,"slug":"insidious","status":"scored"},
"Iron Lung|2026":{"score":54,"slug":"iron-lung","status":"scored"},
"It Comes at Night|2017":{"score":78,"slug":"it-comes-at-night","status":"scored"},
"It Follows|2014":{"score":83,"slug":"it-follows","status":"scored"},
"It's What's Inside|2024":{"score":56,"slug":"its-whats-inside","status":"scored"},
"It|2017":{"score":69,"slug":"it","status":"scored"},
"Jennifer's Body|2009":{"score":47,"slug":"jennifers-body","status":"scored"},
"John Wick|2014":{"score":68,"slug":"john-wick","status":"scored"},
"Joker|2019":{"score":59,"slug":"joker","status":"scored"},
"Joshua|2007":{"score":69,"slug":"joshua","status":"scored"},
"Julia's Eyes|2010":{"score":null,"slug":null,"status":"not-found"},
"Kidnapped|2010":{"score":49,"slug":"kidnapped","status":"scored"},
"Kill List|2011":{"score":67,"slug":"kill-list","status":"scored"},
"Killer Joe|2011":{"score":62,"slug":"killer-joe","status":"scored"},
"Killer Whale|2026":{"score":null,"slug":"killer-whale","status":"no-score"},
"Killing Ground|2016":{"score":59,"slug":"killing-ground","status":"scored"},
"Kimi|2022":{"score":79,"slug":"kimi","status":"scored"},
"Kiss Kiss Bang Bang|2005":{"score":73,"slug":"kiss-kiss-bang-bang","status":"scored"},
"Knife+Heart|2018":{"score":null,"slug":null,"status":"not-found"},
"Knock Knock|2015":{"score":53,"slug":"knock-knock","status":"scored"},
"Knock at the Cabin|2023":{"score":63,"slug":"knock-at-the-cabin","status":"scored"},
"Krampus|2015":{"score":49,"slug":"krampus","status":"scored"},
"La Llorona|2019":{"score":79,"slug":"la-llorona","status":"scored"},
"Lake Mungo|2008":{"score":null,"slug":null,"status":"not-found"},
"Lamb|2021":{"score":62,"slug":"lamb","status":"scored"},
"Last Night in Soho|2021":{"score":65,"slug":"last-night-in-soho","status":"scored"},
"Late Night with the Devil|2023":{"score":72,"slug":"late-night-with-the-devil","status":"scored"},
"Leave the World Behind|2023":{"score":68,"slug":"leave-the-world-behind","status":"scored"},
"Lee Cronin's The Mummy|2026":{"score":47,"slug":"lee-cronins-the-mummy","status":"scored"},
"Let Him Go|2020":{"score":63,"slug":"let-him-go","status":"scored"},
"Let Me In|2010":{"score":79,"slug":"let-me-in","status":"scored"},
"Let the Right One In|2008":{"score":82,"slug":"let-the-right-one-in","status":"scored"},
"Leviticus|2026":{"score":83,"slug":"leviticus","status":"scored"},
"Life|2017":{"score":63,"slug":"life","status":"scored"},
"Lights Out|2016":{"score":58,"slug":"lights-out","status":"scored"},
"Limitless|2011":{"score":59,"slug":"limitless","status":"scored"},
"Locked|2025":{"score":45,"slug":"locked","status":"scored"},
"Locke|2013":{"score":83,"slug":"locke","status":"scored"},
"Longlegs|2024":{"score":77,"slug":"longlegs","status":"scored"},
"Looper|2012":{"score":84,"slug":"looper","status":"scored"},
"Love Lies Bleeding|2024":{"score":77,"slug":"love-lies-bleeding","status":"scored"},
"Lovely Molly|2011":{"score":50,"slug":"lovely-molly","status":"scored"},
"M3GAN|2023":{"score":72,"slug":"m3gan","status":"scored"},
"MaXXXine|2024":{"score":64,"slug":"maxxxine","status":"scored"},
"Mad God|2021":{"score":80,"slug":"mad-god","status":"scored"},
"Malignant|2021":{"score":51,"slug":"malignant","status":"scored"},
"Mama|2013":{"score":57,"slug":"mama","status":"scored"},
"Mandy|2018":{"score":83,"slug":"mandy","status":"scored"},
"Maniac|2012":{"score":47,"slug":"maniac","status":"scored"},
"Martha Marcy May Marlene|2011":{"score":75,"slug":"martha-marcy-may-marlene","status":"scored"},
"Martyrs|2008":{"score":22,"slug":"martyrs","status":"scored"},
"Master|2022":{"score":53,"slug":"master","status":"scored"},
"Match Point|2005":{"score":72,"slug":"match-point","status":"scored"},
"Mayhem|2017":{"score":62,"slug":"mayhem","status":"scored"},
"Memoir of a Murderer|2017":{"score":null,"slug":"memoir-of-a-murderer","status":"no-score"},
"Men|2022":{"score":65,"slug":"men","status":"scored"},
"Michael Clayton|2007":{"score":82,"slug":"michael-clayton","status":"scored"},
"Midsommar|2019":{"score":72,"slug":"midsommar","status":"scored"},
"Mirrors|2008":{"score":35,"slug":"mirrors","status":"scored"},
"Missing|2023":{"score":78,"slug":"missing","status":"scored"},
"Mission: Impossible - Ghost Protocol|2011":{"score":null,"slug":null,"status":"not-found"},
"Mission: Impossible - Rogue Nation|2015":{"score":null,"slug":null,"status":"not-found"},
"Monkey Man|2024":{"score":70,"slug":"monkey-man","status":"scored"},
"Monsters|2010":{"score":63,"slug":"monsters","status":"scored"},
"Moon|2009":{"score":67,"slug":"moon","status":"scored"},
"Mother|2009":{"score":79,"slug":"mother","status":"scored"},
"Mr. Brooks|2007":{"score":45,"slug":"mr-brooks","status":"scored"},
"Nanny|2022":{"score":72,"slug":"nanny","status":"scored"},
"Never Let Go|2024":{"score":55,"slug":"never-let-go","status":"scored"},
"Night Patrol|2026":{"score":53,"slug":"night-patrol","status":"scored"},
"Nightcrawler|2014":{"score":76,"slug":"nightcrawler","status":"scored"},
"No Country for Old Men|2007":{"score":92,"slug":"no-country-for-old-men","status":"scored"},
"No One Will Save You|2023":{"score":60,"slug":"no-one-will-save-you","status":"scored"},
"Nocturnal Animals|2016":{"score":67,"slug":"nocturnal-animals","status":"scored"},
"Non-Stop|2014":{"score":56,"slug":"non-stop","status":"scored"},
"Nope|2022":{"score":77,"slug":"nope","status":"scored"},
"Noroi: The Curse|2005":{"score":null,"slug":null,"status":"not-found"},
"Nosferatu|2024":{"score":null,"slug":"nosferatu","status":"no-score"},
"Novocaine|2025":{"score":45,"slug":"novocaine","status":"scored"},
"Obsession|2026":{"score":null,"slug":"obsession","status":"no-score"},
"Oculus|2013":{"score":61,"slug":"oculus","status":"scored"},
"Oddity|2024":{"score":78,"slug":"oddity","status":"scored"},
"Old|2021":{"score":55,"slug":"old","status":"scored"},
"One Cut of the Dead|2017":{"score":86,"slug":"one-cut-of-the-dead","status":"scored"},
"Only God Forgives|2013":{"score":37,"slug":"only-god-forgives","status":"scored"},
"Orphan: First Kill|2022":{"score":54,"slug":"orphan-first-kill","status":"scored"},
"Orphan|2009":{"score":42,"slug":"orphan","status":"scored"},
"Ouija: Origin of Evil|2016":{"score":65,"slug":"ouija-origin-of-evil","status":"scored"},
"Out of the Furnace|2013":{"score":63,"slug":"out-of-the-furnace","status":"scored"},
"Overlord|2018":{"score":60,"slug":"overlord-2018","status":"scored"},
"Oxygen|2021":{"score":67,"slug":"oxygen","status":"scored"},
"Pan's Labyrinth|2006":{"score":98,"slug":"pans-labyrinth","status":"scored"},
"Pandorum|2009":{"score":28,"slug":"pandorum","status":"scored"},
"Paranormal Activity|2007":{"score":68,"slug":"paranormal-activity","status":"scored"},
"Parasite|2019":{"score":97,"slug":"parasite","status":"scored"},
"Passenger|2026":{"score":52,"slug":"passenger","status":"scored"},
"Pathology|2008":{"score":55,"slug":"pathology","status":"scored"},
"Pearl|2022":{"score":null,"slug":"pearl","status":"no-score"},
"Perfume: The Story of a Murderer|2006":{"score":56,"slug":"perfume-the-story-of-a-murderer","status":"scored"},
"Personal Shopper|2016":{"score":77,"slug":"personal-shopper","status":"scored"},
"Pet Sematary|2019":{"score":38,"slug":"pet-sematary","status":"scored"},
"Pet|2016":{"score":48,"slug":"pet","status":"scored"},
"Piggy|2022":{"score":72,"slug":"piggy","status":"scored"},
"Piranha 3D|2010":{"score":null,"slug":null,"status":"not-found"},
"Pontypool|2008":{"score":54,"slug":"pontypool","status":"scored"},
"Possessor|2020":{"score":null,"slug":null,"status":"not-found"},
"Predestination|2014":{"score":69,"slug":"predestination","status":"scored"},
"Presence|2024":{"score":77,"slug":"presence","status":"scored"},
"Prey|2022":{"score":null,"slug":"prey","status":"no-score"},
"Primate|2026":{"score":58,"slug":"primate","status":"scored"},
"Prisoners|2013":{"score":70,"slug":"prisoners","status":"scored"},
"Prom Night|2008":{"score":17,"slug":"prom-night","status":"scored"},
"Psycho Killer|2026":{"score":26,"slug":"psycho-killer","status":"scored"},
"Pyewacket|2017":{"score":56,"slug":"pyewacket","status":"scored"},
"Quarantine|2008":{"score":53,"slug":"quarantine","status":"scored"},
"Rampant|2018":{"score":null,"slug":"rampant","status":"no-score"},
"Random Acts of Violence|2019":{"score":39,"slug":"random-acts-of-violence","status":"scored"},
"Rare Exports|2010":{"score":null,"slug":null,"status":"not-found"},
"Raw|2016":{"score":81,"slug":"raw","status":"scored"},
"Ready or Not 2: Here I Come|2026":{"score":58,"slug":"ready-or-not-2-here-i-come","status":"scored"},
"Ready or Not|2019":{"score":64,"slug":"ready-or-not","status":"scored"},
"Rebel Ridge|2024":{"score":76,"slug":"rebel-ridge","status":"scored"},
"Red Eye|2005":{"score":71,"slug":"red-eye","status":"scored"},
"Relic|2020":{"score":77,"slug":"relic","status":"scored"},
"Resurrection|2022":{"score":70,"slug":"resurrection","status":"scored"},
"Return to Silent Hill|2026":{"score":34,"slug":"return-to-silent-hill","status":"scored"},
"Revenge|2017":{"score":81,"slug":"revenge","status":"scored"},
"Room|2015":{"score":64,"slug":"room","status":"scored"},
"Run|2020":{"score":67,"slug":"run","status":"scored"},
"Saint Maud|2019":{"score":83,"slug":"saint-maud","status":"scored"},
"Salem's Lot|2024":{"score":47,"slug":"salems-lot","status":"scored"},
"Saw X|2023":{"score":60,"slug":"saw-x","status":"scored"},
"Scary Movie|2026":{"score":48,"slug":"scary-movie","status":"scored"},
"Scary Stories to Tell in the Dark|2019":{"score":61,"slug":"scary-stories-to-tell-in-the-dark","status":"scored"},
"Scream 7|2026":{"score":35,"slug":"scream-7","status":"scored"},
"Scream VI|2023":{"score":61,"slug":"scream-vi","status":"scored"},
"Scream|2022":{"score":66,"slug":"scream","status":"scored"},
"Searching|2018":{"score":71,"slug":"searching","status":"scored"},
"Send Help|2026":{"score":75,"slug":"send-help","status":"scored"},
"Severance|2006":{"score":62,"slug":"severance","status":"scored"},
"She Will|2021":{"score":73,"slug":"she-will","status":"scored"},
"Shooter|2007":{"score":53,"slug":"shooter","status":"scored"},
"Shutter Island|2010":{"score":63,"slug":"shutter-island","status":"scored"},
"Shutter|2008":{"score":37,"slug":"shutter","status":"scored"},
"Sicario|2015":{"score":82,"slug":"sicario","status":"scored"},
"Sick|2022":{"score":62,"slug":"sick","status":"scored"},
"Side Effects|2013":{"score":46,"slug":"side-effects","status":"scored"},
"Silent Hill: Revelation|2012":{"score":null,"slug":null,"status":"not-found"},
"Silent House|2011":{"score":49,"slug":"silent-house","status":"scored"},
"Sinister|2012":{"score":53,"slug":"sinister-2012","status":"scored"},
"Sinners|2025":{"score":84,"slug":"sinners","status":"scored"},
"Skinamarink|2022":{"score":66,"slug":"skinamarink","status":"scored"},
"Skyfall|2012":{"score":81,"slug":"skyfall","status":"scored"},
"Sleep Tight|2011":{"score":70,"slug":"sleep-tight","status":"scored"},
"Slither|2006":{"score":67,"slug":"slither","status":"scored"},
"Smile|2022":{"score":47,"slug":"smile","status":"scored"},
"Snowpiercer|2013":{"score":84,"slug":"snowpiercer","status":"scored"},
"Snowtown|2011":{"score":null,"slug":null,"status":"not-found"},
"Soft & Quiet|2022":{"score":82,"slug":"soft-quiet","status":"scored"},
"Sorority Row|2009":{"score":24,"slug":"sorority-row","status":"scored"},
"Source Code|2011":{"score":74,"slug":"source-code","status":"scored"},
"Southbound|2015":{"score":58,"slug":"southbound","status":"scored"},
"Speak No Evil|2022":{"score":78,"slug":"speak-no-evil","status":"scored"},
"Speak No Evil|2024":{"score":78,"slug":"speak-no-evil","status":"scored"},
"Spiral|2021":{"score":40,"slug":"spiral","status":"scored"},
"Splinter|2008":{"score":58,"slug":"splinter","status":"scored"},
"Split|2016":{"score":63,"slug":"split","status":"scored"},
"Spree|2020":{"score":42,"slug":"spree","status":"scored"},
"Sputnik|2020":{"score":61,"slug":"sputnik","status":"scored"},
"Stake Land|2010":{"score":66,"slug":"stake-land","status":"scored"},
"Starfish|2018":{"score":74,"slug":"starfish","status":"scored"},
"Starry Eyes|2014":{"score":49,"slug":"starry-eyes","status":"scored"},
"Sting|2024":{"score":57,"slug":"sting","status":"scored"},
"Stoker|2013":{"score":58,"slug":"stoker","status":"scored"},
"Stopmotion|2023":{"score":65,"slug":"stopmotion","status":"scored"},
"Strange Darling|2024":{"score":80,"slug":"strange-darling","status":"scored"},
"Summer of 84|2018":{"score":57,"slug":"summer-of-84","status":"scored"},
"Sunshine|2007":{"score":64,"slug":"sunshine","status":"scored"},
"Super Dark Times|2017":{"score":75,"slug":"super-dark-times","status":"scored"},
"Suspiria|2018":{"score":79,"slug":"suspiria","status":"scored"},
"Swallow|2019":{"score":65,"slug":"swallow","status":"scored"},
"Sympathy for Lady Vengeance|2005":{"score":null,"slug":null,"status":"not-found"},
"Synchronic|2019":{"score":64,"slug":"synchronic","status":"scored"},
"Take Shelter|2011":{"score":85,"slug":"take-shelter","status":"scored"},
"Taken|2008":{"score":51,"slug":"taken","status":"scored"},
"Talk to Me|2023":{"score":69,"slug":"talk-to-me","status":"scored"},
"Tarot|2024":{"score":36,"slug":"tarot","status":"scored"},
"Teeth|2007":{"score":57,"slug":"teeth","status":"scored"},
"Tell No One|2006":{"score":82,"slug":"tell-no-one","status":"scored"},
"Thanksgiving|2023":{"score":63,"slug":"thanksgiving","status":"scored"},
"The Accountant|2016":{"score":51,"slug":"the-accountant","status":"scored"},
"The Age of Shadows|2016":{"score":78,"slug":"the-age-of-shadows","status":"scored"},
"The American|2010":{"score":61,"slug":"the-american","status":"scored"},
"The Amityville Horror|2005":{"score":33,"slug":"the-amityville-horror","status":"scored"},
"The Autopsy of Jane Doe|2016":{"score":65,"slug":"the-autopsy-of-jane-doe","status":"scored"},
"The Awakening|2011":{"score":53,"slug":"the-awakening","status":"scored"},
"The Babadook|2014":{"score":86,"slug":"the-babadook","status":"scored"},
"The Babysitter|2017":{"score":null,"slug":"the-babysitter","status":"no-score"},
"The Batman|2022":{"score":72,"slug":"the-batman","status":"scored"},
"The Bay|2012":{"score":65,"slug":"the-bay","status":"scored"},
"The Beekeeper|2024":{"score":53,"slug":"the-beekeeper","status":"scored"},
"The Beta Test|2021":{"score":72,"slug":"the-beta-test","status":"scored"},
"The Black Phone|2021":{"score":65,"slug":"the-black-phone","status":"scored"},
"The Blackening|2022":{"score":67,"slug":"the-blackening","status":"scored"},
"The Boogeyman|2023":{"score":55,"slug":"the-boogeyman","status":"scored"},
"The Borderlands|2013":{"score":null,"slug":null,"status":"not-found"},
"The Bourne Ultimatum|2007":{"score":85,"slug":"the-bourne-ultimatum","status":"scored"},
"The Boy|2016":{"score":42,"slug":"the-boy","status":"scored"},
"The Brave One|2007":{"score":56,"slug":"the-brave-one","status":"scored"},
"The Bride!|2026":{"score":55,"slug":"the-bride-2026","status":"scored"},
"The Cabin in the Woods|2012":{"score":72,"slug":"the-cabin-in-the-woods","status":"scored"},
"The Call|2020":{"score":51,"slug":"the-call","status":"scored"},
"The Canal|2014":{"score":55,"slug":"the-canal","status":"scored"},
"The Canyon|2009":{"score":null,"slug":null,"status":"not-found"},
"The Cave|2005":{"score":30,"slug":"the-cave","status":"scored"},
"The Chaser|2008":{"score":64,"slug":"the-chaser","status":"scored"},
"The Children|2008":{"score":null,"slug":null,"status":"not-found"},
"The Clovehitch Killer|2018":{"score":59,"slug":"the-clovehitch-killer","status":"scored"},
"The Collector|2009":{"score":29,"slug":"the-collector","status":"scored"},
"The Conjuring|2013":{"score":68,"slug":"the-conjuring","status":"scored"},
"The Constant Gardener|2005":{"score":82,"slug":"the-constant-gardener","status":"scored"},
"The Crazies|2010":{"score":56,"slug":"the-crazies","status":"scored"},
"The Cursed|2021":{"score":62,"slug":"the-cursed","status":"scored"},
"The Da Vinci Code|2006":{"score":46,"slug":"the-da-vinci-code","status":"scored"},
"The Dark Knight|2008":{"score":85,"slug":"the-dark-knight","status":"scored"},
"The Dark and the Wicked|2020":{"score":72,"slug":"the-dark-and-the-wicked","status":"scored"},
"The Deliverance|2024":{"score":39,"slug":"the-deliverance","status":"scored"},
"The Den|2013":{"score":48,"slug":"the-den","status":"scored"},
"The Departed|2006":{"score":85,"slug":"the-departed","status":"scored"},
"The Descent|2005":{"score":71,"slug":"the-descent","status":"scored"},
"The Devil's Candy|2015":{"score":72,"slug":"the-devils-candy","status":"scored"},
"The Devil's Rejects|2005":{"score":54,"slug":"the-devils-rejects","status":"scored"},
"The Djinn|2021":{"score":59,"slug":"the-djinn","status":"scored"},
"The Double|2013":{"score":37,"slug":"the-double","status":"scored"},
"The Drop|2014":{"score":69,"slug":"the-drop","status":"scored"},
"The Dry|2020":{"score":69,"slug":"the-dry","status":"scored"},
"The East|2013":{"score":68,"slug":"the-east","status":"scored"},
"The Endless|2017":{"score":80,"slug":"the-endless","status":"scored"},
"The Equalizer|2014":{"score":57,"slug":"the-equalizer","status":"scored"},
"The Exorcism of Emily Rose|2005":{"score":46,"slug":"the-exorcism-of-emily-rose","status":"scored"},
"The Eye|2008":{"score":36,"slug":"the-eye","status":"scored"},
"The Final Girls|2015":{"score":59,"slug":"the-final-girls","status":"scored"},
"The First Omen|2024":{"score":65,"slug":"the-first-omen","status":"scored"},
"The Fog|2005":{"score":27,"slug":"the-fog","status":"scored"},
"The Forever Purge|2021":{"score":53,"slug":"the-forever-purge","status":"scored"},
"The Ghost Writer|2010":{"score":77,"slug":"the-ghost-writer","status":"scored"},
"The Gift|2015":{"score":62,"slug":"the-gift","status":"scored"},
"The Girl Next Door|2007":{"score":29,"slug":"the-girl-next-door","status":"scored"},
"The Girl with All the Gifts|2016":{"score":67,"slug":"the-girl-with-all-the-gifts","status":"scored"},
"The Girl with the Dragon Tattoo|2009":{"score":76,"slug":"the-girl-with-the-dragon-tattoo","status":"scored"},
"The Girl with the Dragon Tattoo|2011":{"score":76,"slug":"the-girl-with-the-dragon-tattoo","status":"scored"},
"The Good Shepherd|2006":{"score":61,"slug":"the-good-shepherd","status":"scored"},
"The Gorge|2025":{"score":57,"slug":"the-gorge","status":"scored"},
"The Grey|2011":{"score":64,"slug":"the-grey","status":"scored"},
"The Grudge 2|2006":{"score":33,"slug":"the-grudge-2","status":"scored"},
"The Guest|2014":{"score":76,"slug":"the-guest","status":"scored"},
"The Guilty|2018":{"score":83,"slug":"the-guilty","status":"scored"},
"The Guilty|2021":{"score":83,"slug":"the-guilty","status":"scored"},
"The Hallow|2015":{"score":65,"slug":"the-hallow","status":"scored"},
"The Handmaiden|2016":{"score":85,"slug":"the-handmaiden","status":"scored"},
"The Harbinger|2022":{"score":70,"slug":"the-harbinger","status":"scored"},
"The Hills Have Eyes|2006":{"score":52,"slug":"the-hills-have-eyes","status":"scored"},
"The Hole in the Ground|2019":{"score":63,"slug":"the-hole-in-the-ground","status":"scored"},
"The Host|2006":{"score":85,"slug":"the-host","status":"scored"},
"The House That Jack Built|2018":{"score":null,"slug":"the-house-that-jack-built","status":"no-score"},
"The House of the Devil|2009":{"score":73,"slug":"the-house-of-the-devil","status":"scored"},
"The Housemaid|2010":{"score":68,"slug":"the-housemaid","status":"scored"},
"The Hunt|2012":{"score":77,"slug":"the-hunt","status":"scored"},
"The Hunt|2020":{"score":77,"slug":"the-hunt","status":"scored"},
"The Iceman|2012":{"score":60,"slug":"the-iceman","status":"scored"},
"The Illusionist|2006":{"score":68,"slug":"the-illusionist","status":"scored"},
"The Imposter|2012":{"score":77,"slug":"the-imposter","status":"scored"},
"The Innkeepers|2011":{"score":64,"slug":"the-innkeepers","status":"scored"},
"The Innocents|2021":{"score":88,"slug":"the-innocents","status":"scored"},
"The Invisible Man|2020":{"score":72,"slug":"the-invisible-man","status":"scored"},
"The Invitation|2015":{"score":74,"slug":"the-invitation","status":"scored"},
"The Jacket|2005":{"score":44,"slug":"the-jacket","status":"scored"},
"The Killer Inside Me|2010":{"score":53,"slug":"the-killer-inside-me","status":"scored"},
"The Killer|2023":{"score":82,"slug":"the-killer","status":"scored"},
"The Killing of a Sacred Deer|2017":{"score":73,"slug":"the-killing-of-a-sacred-deer","status":"scored"},
"The Lair|2022":{"score":41,"slug":"the-lair","status":"scored"},
"The Last Exorcism|2010":{"score":63,"slug":"the-last-exorcism","status":"scored"},
"The Last House on the Left|2009":{"score":42,"slug":"the-last-house-on-the-left","status":"scored"},
"The Last King of Scotland|2006":{"score":74,"slug":"the-last-king-of-scotland","status":"scored"},
"The Lighthouse|2019":{"score":58,"slug":"the-lighthouse","status":"scored"},
"The Lincoln Lawyer|2011":{"score":63,"slug":"the-lincoln-lawyer","status":"scored"},
"The Lives of Others|2006":{"score":89,"slug":"the-lives-of-others","status":"scored"},
"The Lodge|2019":{"score":64,"slug":"the-lodge","status":"scored"},
"The Lords of Salem|2012":{"score":57,"slug":"the-lords-of-salem","status":"scored"},
"The Loved Ones|2009":{"score":73,"slug":"the-loved-ones","status":"scored"},
"The Manor|2021":{"score":59,"slug":"the-manor","status":"scored"},
"The Medium|2021":{"score":null,"slug":"the-medium","status":"no-score"},
"The Meg|2018":{"score":46,"slug":"the-meg","status":"scored"},
"The Menu|2022":{"score":71,"slug":"the-menu","status":"scored"},
"The Midnight Meat Train|2008":{"score":58,"slug":"the-midnight-meat-train","status":"scored"},
"The Mist|2007":{"score":58,"slug":"the-mist","status":"scored"},
"The Monkey|2025":{"score":62,"slug":"the-monkey","status":"scored"},
"The Monster|2016":{"score":69,"slug":"the-monster","status":"scored"},
"The Mortuary Collection|2019":{"score":69,"slug":"the-mortuary-collection","status":"scored"},
"The Neon Demon|2016":{"score":51,"slug":"the-neon-demon","status":"scored"},
"The Night Comes for Us|2018":{"score":69,"slug":"the-night-comes-for-us","status":"scored"},
"The Night Eats the World|2018":{"score":50,"slug":"the-night-eats-the-world","status":"scored"},
"The Night House|2020":{"score":68,"slug":"the-night-house","status":"scored"},
"The Nightingale|2018":{"score":67,"slug":"the-nightingale","status":"scored"},
"The Northman|2022":{"score":82,"slug":"the-northman","status":"scored"},
"The Offering|2022":{"score":14,"slug":"the-offering","status":"scored"},
"The Omen|2006":{"score":43,"slug":"the-omen","status":"scored"},
"The One I Love|2014":{"score":66,"slug":"the-one-i-love","status":"scored"},
"The Order|2024":{"score":21,"slug":"the-order","status":"scored"},
"The Orphanage|2007":{"score":74,"slug":"the-orphanage","status":"scored"},
"The Outfit|2022":{"score":69,"slug":"the-outfit","status":"scored"},
"The Pact|2012":{"score":54,"slug":"the-pact","status":"scored"},
"The Perfection|2018":{"score":60,"slug":"the-perfection","status":"scored"},
"The Platform|2019":{"score":73,"slug":"the-platform","status":"scored"},
"The Pope's Exorcist|2023":{"score":45,"slug":"the-popes-exorcist","status":"scored"},
"The Possession|2012":{"score":45,"slug":"the-possession","status":"scored"},
"The Poughkeepsie Tapes|2007":{"score":null,"slug":null,"status":"not-found"},
"The Power|2021":{"score":60,"slug":"the-power","status":"scored"},
"The Prestige|2006":{"score":66,"slug":"the-prestige","status":"scored"},
"The Prodigy|2019":{"score":45,"slug":"the-prodigy","status":"scored"},
"The Proposition|2005":{"score":73,"slug":"the-proposition","status":"scored"},
"The Purge: Anarchy|2014":{"score":50,"slug":"the-purge-anarchy","status":"scored"},
"The Purge: Election Year|2016":{"score":55,"slug":"the-purge-election-year","status":"scored"},
"The Purge|2013":{"score":41,"slug":"the-purge","status":"scored"},
"The Raid 2|2014":{"score":71,"slug":"the-raid-2","status":"scored"},
"The Raid: Redemption|2011":{"score":73,"slug":"the-raid-redemption","status":"scored"},
"The Reef|2010":{"score":null,"slug":null,"status":"not-found"},
"The Rental|2020":{"score":62,"slug":"the-rental","status":"scored"},
"The Revenant|2015":{"score":57,"slug":"the-revenant","status":"scored"},
"The Ritual|2017":{"score":57,"slug":"the-ritual","status":"scored"},
"The Road|2009":{"score":64,"slug":"the-road","status":"scored"},
"The Rover|2014":{"score":64,"slug":"the-rover","status":"scored"},
"The Rule of Jenny Pen|2024":{"score":66,"slug":"the-rule-of-jenny-pen","status":"scored"},
"The Sacrament|2013":{"score":49,"slug":"the-sacrament","status":"scored"},
"The Sadness|2021":{"score":68,"slug":"the-sadness","status":"scored"},
"The Salesman|2016":{"score":85,"slug":"the-salesman","status":"scored"},
"The Secret in Their Eyes|2009":{"score":80,"slug":"the-secret-in-their-eyes","status":"scored"},
"The Shallows|2016":{"score":59,"slug":"the-shallows","status":"scored"},
"The Signal|2007":{"score":63,"slug":"the-signal","status":"scored"},
"The Signal|2014":{"score":63,"slug":"the-signal","status":"scored"},
"The Skeleton Key|2005":{"score":47,"slug":"the-skeleton-key","status":"scored"},
"The Skin I Live In|2011":{"score":70,"slug":"the-skin-i-live-in","status":"scored"},
"The Square|2008":{"score":75,"slug":"the-square","status":"scored"},
"The Stanford Prison Experiment|2015":{"score":67,"slug":"the-stanford-prison-experiment","status":"scored"},
"The Strangers: Chapter 1|2024":{"score":43,"slug":"the-strangers-chapter-1","status":"scored"},
"The Strangers: Chapter 3|2026":{"score":19,"slug":"the-strangers-chapter-3","status":"scored"},
"The Strangers|2008":{"score":47,"slug":"the-strangers","status":"scored"},
"The Stranger|2022":{"score":32,"slug":"the-stranger","status":"scored"},
"The Substance|2024":{"score":78,"slug":"the-substance","status":"scored"},
"The Taking of Deborah Logan|2014":{"score":null,"slug":null,"status":"not-found"},
"The Tall Man|2012":{"score":52,"slug":"the-tall-man","status":"scored"},
"The Thing|2011":{"score":49,"slug":"the-thing","status":"scored"},
"The Town|2010":{"score":74,"slug":"the-town","status":"scored"},
"The Trip|2021":{"score":47,"slug":"the-trip","status":"scored"},
"The Uninvited|2009":{"score":43,"slug":"the-uninvited","status":"scored"},
"The Vanishing|2018":{"score":49,"slug":"the-vanishing","status":"scored"},
"The Vast of Night|2019":{"score":84,"slug":"the-vast-of-night","status":"scored"},
"The Vigil|2019":{"score":69,"slug":"the-vigil","status":"scored"},
"The Villainess|2017":{"score":64,"slug":"the-villainess","status":"scored"},
"The Visit|2015":{"score":60,"slug":"the-visit","status":"scored"},
"The Voyeurs|2021":{"score":54,"slug":"the-voyeurs","status":"scored"},
"The Wailing|2016":{"score":81,"slug":"the-wailing","status":"scored"},
"The Ward|2010":{"score":38,"slug":"the-ward","status":"scored"},
"The Wasp|2024":{"score":69,"slug":"the-wasp","status":"scored"},
"The Wasteland|2021":{"score":null,"slug":"the-wasteland","status":"no-score"},
"The Watchers|2024":{"score":46,"slug":"the-watchers","status":"scored"},
"The Wave|2015":{"score":68,"slug":"the-wave","status":"scored"},
"The Witch|2015":{"score":84,"slug":"the-witch","status":"scored"},
"The Wolf of Snow Hollow|2020":{"score":67,"slug":"the-wolf-of-snow-hollow","status":"scored"},
"The Woman in Black|2012":{"score":62,"slug":"the-woman-in-black","status":"scored"},
"The Woman in the Yard|2025":{"score":51,"slug":"the-woman-in-the-yard","status":"scored"},
"The Woman|2011":{"score":58,"slug":"the-woman","status":"scored"},
"The Wrath of Becky|2023":{"score":51,"slug":"the-wrath-of-becky","status":"scored"},
"The Wretched|2019":{"score":61,"slug":"the-wretched","status":"scored"},
"Thelma|2017":{"score":74,"slug":"thelma","status":"scored"},
"Them|2006":{"score":60,"slug":"them","status":"scored"},
"They Will Kill You|2026":{"score":50,"slug":"they-will-kill-you","status":"scored"},
"Thirst|2009":{"score":73,"slug":"thirst","status":"scored"},
"Thoroughbreds|2017":{"score":75,"slug":"thoroughbreds","status":"scored"},
"Tigers Are Not Afraid|2017":{"score":76,"slug":"tigers-are-not-afraid","status":"scored"},
"Timecrimes|2007":{"score":68,"slug":"timecrimes","status":"scored"},
"Tinker Tailor Soldier Spy|2011":{"score":85,"slug":"tinker-tailor-soldier-spy","status":"scored"},
"Titane|2021":{"score":75,"slug":"titane","status":"scored"},
"Totally Killer|2023":{"score":62,"slug":"totally-killer","status":"scored"},
"Tragedy Girls|2017":{"score":58,"slug":"tragedy-girls","status":"scored"},
"Train to Busan|2016":{"score":73,"slug":"train-to-busan","status":"scored"},
"Trance|2013":{"score":61,"slug":"trance","status":"scored"},
"Transsiberian|2008":{"score":72,"slug":"transsiberian","status":"scored"},
"Trap|2024":{"score":52,"slug":"trap","status":"scored"},
"Triangle|2009":{"score":null,"slug":null,"status":"not-found"},
"Trick r Treat|2007":{"score":null,"slug":"trick-r-treat","status":"no-score"},
"Tucker & Dale vs Evil|2010":{"score":65,"slug":"tucker-dale-vs-evil","status":"scored"},
"Tucker and Dale vs Evil|2010":{"score":65,"slug":"tucker-dale-vs-evil","status":"scored"},
"Turistas|2006":{"score":36,"slug":"turistas","status":"scored"},
"Twisters|2024":{"score":65,"slug":"twisters","status":"scored"},
"Uncut Gems|2019":{"score":93,"slug":"uncut-gems","status":"scored"},
"Under the Shadow|2016":{"score":83,"slug":"under-the-shadow","status":"scored"},
"Undertone|2026":{"score":64,"slug":"undertone","status":"scored"},
"Unfriended|2014":{"score":59,"slug":"unfriended","status":"scored"},
"Unhinged|2020":{"score":40,"slug":"unhinged","status":"scored"},
"United 93|2006":{"score":90,"slug":"united-93","status":"scored"},
"Unsane|2018":{"score":63,"slug":"unsane","status":"scored"},
"Upgrade|2018":{"score":67,"slug":"upgrade","status":"scored"},
"Us|2019":{"score":81,"slug":"us","status":"scored"},
"V/H/S/85|2023":{"score":null,"slug":null,"status":"not-found"},
"V/H/S/94|2021":{"score":null,"slug":null,"status":"not-found"},
"V/H/S/99|2022":{"score":null,"slug":null,"status":"not-found"},
"V/H/S|2012":{"score":null,"slug":null,"status":"not-found"},
"Victoria|2015":{"score":77,"slug":"victoria","status":"scored"},
"Villains|2019":{"score":63,"slug":"villains","status":"scored"},
"Watcher|2022":{"score":72,"slug":"watcher","status":"scored"},
"We Are What We Are|2013":{"score":65,"slug":"we-are-what-we-are","status":"scored"},
"We Bury the Dead|2026":{"score":61,"slug":"we-bury-the-dead","status":"scored"},
"We Need to Talk About Kevin|2011":{"score":68,"slug":"we-need-to-talk-about-kevin","status":"scored"},
"Weapons|2025":{"score":81,"slug":"weapons","status":"scored"},
"Werewolves Within|2021":{"score":66,"slug":"werewolves-within","status":"scored"},
"Wheelman|2017":{"score":66,"slug":"wheelman","status":"scored"},
"When Evil Lurks|2023":{"score":75,"slug":"when-evil-lurks","status":"scored"},
"When a Stranger Calls|2006":{"score":27,"slug":"when-a-stranger-calls","status":"scored"},
"Whistle|2026":{"score":55,"slug":"whistle","status":"scored"},
"Wind River|2017":{"score":73,"slug":"wind-river","status":"scored"},
"Wolf Creek|2005":{"score":56,"slug":"wolf-creek","status":"scored"},
"Wolf Man|2025":{"score":50,"slug":"wolf-man","status":"scored"},
"Woman of the Hour|2023":{"score":74,"slug":"woman-of-the-hour","status":"scored"},
"World War Z|2013":{"score":63,"slug":"world-war-z","status":"scored"},
"X|2022":{"score":40,"slug":"x","status":"scored"},
"You Won't Be Alone|2022":{"score":82,"slug":"you-wont-be-alone","status":"scored"},
"You're Next|2011":{"score":66,"slug":"youre-next","status":"scored"},
"Zero Dark Thirty|2012":{"score":95,"slug":"zero-dark-thirty","status":"scored"},
"Zodiac|2007":{"score":79,"slug":"zodiac","status":"scored"},
"Zombieland: Double Tap|2019":{"score":55,"slug":"zombieland-double-tap","status":"scored"},
"[REC]|2007":{"score":71,"slug":"rec","status":"scored"},
"mother!|2017":{"score":79,"slug":"mother","status":"scored"},
};
